
# Loads default set of integrations. Do not remove.
#default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#automation: !include automations.yaml
automation: !include_dir_merge_list automations/
#script: !include scripts.yaml
#scene: !include scenes.yaml

#knx: !include knx/all.yaml

logger:
  default: info
#  logs:
#    custom_components.shadow_control: debug
#    custom_components.shadow_control.config_flow: debug

input_boolean: !include_dir_merge_named input_boolean/
input_button: !include_dir_merge_named input_button/
input_number: !include_dir_merge_named input_number/
input_select: !include_dir_merge_named input_select/

template: !include_dir_list template/

shadow_control:
  # =========================================================================
  - name: "SC Dummy"
    debug_enabled: false
    target_cover_entity:
      - cover.test_shutter
    facade_shutter_type_static: mode1

    # Dynamic configuration inputs
    brightness_entity: input_number.d01_brightness
    #brightness_dawn_entity:
    sun_elevation_entity: input_number.d03_sun_elevation
    sun_azimuth_entity: input_number.d04_sun_azimuth
    #sunrise_entity:
    #sunset_entity:

    lock_integration_manual: false
    lock_integration_entity: input_boolean.d07_lock_integration
    lock_integration_with_position_manual: false
    lock_integration_with_position_entity: input_boolean.d08_lock_integration_with_position
    lock_height_manual: 50
    lock_height_entity: input_number.lock_height_sc_dummy
    lock_angle_manual: 50
    lock_angle_entity: input_number.lock_angle_sc_dummy
    unlock_integration_entity: input_button.d14_unlock_instances

    # no_restriction, only_open, only_close
    movement_restriction_height_manual: no_restriction
    movement_restriction_angle_manual: no_restriction
    #movement_restriction_height_entity:
    #movement_restriction_angle_entity:

    enforce_positioning_entity: input_button.d13_enforce_positioning

    # General facade configuration
    facade_azimuth_static: 200
    facade_offset_sun_in_static: -45
    facade_offset_sun_out_static: 45
    facade_elevation_sun_min_static: 23
    facade_elevation_sun_max_static: 80
    facade_slat_width_static: 60
    facade_slat_distance_static: 50
    facade_slat_angle_offset_static: 0
    facade_slat_min_angle_static: 0
    facade_shutter_stepping_height_static: 5
    facade_shutter_stepping_angle_static: 5
    facade_light_strip_width_static: 0
    facade_shutter_height_static: 1000
    facade_neutral_pos_height_manual: 0
    facade_neutral_pos_height_entity: input_number.g15_neutral_pos_height
    facade_neutral_pos_angle_manual: 0
    facade_neutral_pos_angle_entity: input_number.g16_neutral_pos_angle
    facade_modification_tolerance_height_static: 3
    facade_modification_tolerance_angle_static: 3

    # Shadow configuration
    #shadow_control_enabled_entity:
    shadow_control_enabled_manual: true
    #shadow_brightness_threshold_winter_entity:
    #shadow_brightness_threshold_winter_manual: 30000
    #shadow_brightness_threshold_summer_entity:
    #shadow_brightness_threshold_summer_manual: 50000
    #shadow_brightness_threshold_minimal_entity:
    #shadow_brightness_threshold_minimal_manual: 1000
    #shadow_after_seconds_entity:
    shadow_after_seconds_manual: 10
    shadow_shutter_max_height_entity: input_number.automation_shadow_max_height_sc_dummy
    shadow_shutter_max_height_manual: 90
    shadow_shutter_max_angle_entity: input_number.automation_shadow_max_angle_sc_dummy
    shadow_shutter_max_angle_manual: 90
    #shadow_shutter_look_through_seconds_entity:
    shadow_shutter_look_through_seconds_manual: 10
    #shadow_shutter_open_seconds_entity:
    shadow_shutter_open_seconds_manual: 10
    #shadow_shutter_look_through_angle_entity:
    shadow_shutter_look_through_angle_manual: 54
    #shadow_height_after_sun_entity:
    shadow_height_after_sun_manual: 80
    #shadow_angle_after_sun_entity:
    shadow_angle_after_sun_manual: 80

    # Dawn configuration
    #dawn_control_enabled_entity:
    dawn_control_enabled_manual: true
    #dawn_brightness_threshold_entity:
    dawn_brightness_threshold_manual: 5000
    #dawn_after_seconds_entity:
    dawn_after_seconds_manual: 10
    dawn_shutter_max_height_entity: input_number.automation_dawn_max_height_sc_dummy
    dawn_shutter_max_height_manual: 90
    dawn_shutter_max_angle_entity: input_number.automation_dawn_max_angle_sc_dummy
    dawn_shutter_max_angle_manual: 90
    #dawn_shutter_look_through_seconds_entity:
    dawn_shutter_look_through_seconds_manual: 10
    #dawn_shutter_open_seconds_entity:
    dawn_shutter_open_seconds_manual: 10
    #dawn_shutter_look_through_angle_entity:
    dawn_shutter_look_through_angle_manual: 45
    #dawn_height_after_dawn_entity:
    dawn_height_after_dawn_manual: 10
    #dawn_angle_after_dawn_entity:
    dawn_angle_after_dawn_manual: 10
    #
    # ========================================================================
    # Deprecated options
    # Since config version 5
    #shadow_brightness_threshold_manual: 30000
    #shadow_brightness_threshold_entity: input_number.deprecated_key
    #lock_integration_static: true
    #lock_integration_with_position_static: true
    #lock_height_static: 42
    #lock_angle_static: 42
    #movement_restriction_height_static: only_open
    #movement_restriction_angle_static: only_close
    #facade_neutral_pos_height_static: 42
    #facade_neutral_pos_angle_static: 42
    #shadow_control_enabled_static: 42
    #shadow_brightness_threshold_static: 42
    #shadow_after_seconds_static: 42
    #shadow_shutter_max_height_static: 42
    #shadow_shutter_max_angle_static: 42
    #shadow_shutter_look_through_seconds_static: 42
    #shadow_shutter_open_seconds_static: 42
    #shadow_shutter_look_through_angle_static: 42
    #shadow_height_after_sun_static: 42
    #shadow_angle_after_sun_static: 42
    #dawn_control_enabled_static: 42
    #dawn_brightness_threshold_static: 42
    #dawn_after_seconds_static: 42
    #dawn_shutter_max_height_static: 42
    #dawn_shutter_max_angle_static: 42
    #dawn_shutter_look_through_seconds_static: 42
    #dawn_shutter_open_seconds_static: 42
    #dawn_shutter_look_through_angle_static: 42
    #dawn_height_after_dawn_static: 42
    #dawn_angle_after_dawn_static: 42
    #
    # ========================================================================
    # Unknown options to check error handling
    #foobar: 23

  # =========================================================================
#  - name: "SC Dummy 2"
#    debug_enabled: false
#    target_cover_entity:
#      - cover.sc_dummy2
#    facade_shutter_type_static: mode1
#    # Dynamic configuration inputs
#    brightness_entity: input_number.d01_brightness
#    #brightness_dawn_entity:
#    sun_elevation_entity: input_number.d03_sun_elevation
#    sun_azimuth_entity: input_number.d04_sun_azimuth
#    #sunrise_entity:
#    #sunset_entity:
#    #lock_integration_manual: false
#    #lock_integration_entity: input_boolean.d07_lock_integration
#    #lock_integration_with_position_manual: false
#    #lock_integration_with_position_entity: input_boolean.d08_lock_integration_with_position
#    #lock_height_manual: 0
#    #lock_height_entity: input_number.lock_height_sc_dummy2
#    #lock_angle_manual: 0
#    #lock_angle_entity: input_number.lock_angle_sc_dummy2
#    unlock_integration_entity: input_button.d14_unlock_instances
#    #movement_restriction_height_manual: no_restriction
#    #movement_restriction_height_entity:
#    #movement_restriction_angle_manual: no_restriction
#    #movement_restriction_angle_entity:
#    enforce_positioning_entity: input_button.d13_enforce_positioning
#    # General facade configuration
#    facade_azimuth_static: 80
#    facade_offset_sun_in_static: -45
#    facade_offset_sun_out_static: 45
#    facade_elevation_sun_min_static: 23
#    facade_elevation_sun_max_static: 80
#    facade_slat_width_static: 60
#    facade_slat_distance_static: 50
#    facade_slat_angle_offset_static: 0
#    facade_slat_min_angle_static: 0
#    facade_shutter_stepping_height_static: 5
#    facade_shutter_stepping_angle_static: 5
#    facade_light_strip_width_static: 0
#    facade_shutter_height_static: 1000
#    facade_neutral_pos_height_manual: 20
#    #facade_neutral_pos_height_entity:
#    facade_neutral_pos_angle_manual: 20
#    #facade_neutral_pos_angle_entity:
#    facade_modification_tolerance_height_static: 3
#    facade_modification_tolerance_angle_static: 3
#    # Shadow configuration
#    #shadow_control_enabled_entity:
#    shadow_control_enabled_manual: true
#    #shadow_brightness_threshold_winter_entity:
#    #shadow_brightness_threshold_winter_manual: 30000
#    #shadow_brightness_threshold_summer_entity:
#    #shadow_brightness_threshold_summer_manual: 50000
#    #shadow_brightness_threshold_minimal_entity:
#    #shadow_brightness_threshold_minimal_manual: 1000
#    #shadow_after_seconds_entity:
#    shadow_after_seconds_manual: 10
#    #shadow_shutter_max_height_entity:
#    shadow_shutter_max_height_manual: 90
#    #shadow_shutter_max_angle_entity:
#    shadow_shutter_max_angle_manual: 90
#    #shadow_shutter_look_through_seconds_entity:
#    shadow_shutter_look_through_seconds_manual: 10
#    #shadow_shutter_open_seconds_entity:
#    shadow_shutter_open_seconds_manual: 10
#    #shadow_shutter_look_through_angle_entity:
#    shadow_shutter_look_through_angle_manual: 50
#    #shadow_height_after_sun_entity:
#    shadow_height_after_sun_manual: 10
#    #shadow_angle_after_sun_entity:
#    shadow_angle_after_sun_manual: 10
#    # Dawn configuration
#    #dawn_control_enabled_entity:
#    dawn_control_enabled_manual: true
#    #dawn_brightness_threshold_entity:
#    dawn_brightness_threshold_manual: 5000
#    #dawn_after_seconds_entity:
#    dawn_after_seconds_manual: 10
#    #dawn_shutter_max_height_entity:
#    dawn_shutter_max_height_manual: 50
#    #dawn_shutter_max_angle_entity:
#    dawn_shutter_max_angle_manual: 50
#    #dawn_shutter_look_through_seconds_entity:
#    dawn_shutter_look_through_seconds_manual: 10
#    #dawn_shutter_open_seconds_entity:
#    dawn_shutter_open_seconds_manual: 10
#    #dawn_shutter_look_through_angle_entity:
#    dawn_shutter_look_through_angle_manual: 45
#    #dawn_height_after_dawn_entity:
#    dawn_height_after_dawn_manual: 80
#    #dawn_angle_after_dawn_entity:
#    dawn_angle_after_dawn_manual: 80

  # =========================================================================
#  - name: "SC Dummy 3"
#    debug_enabled: false
#    target_cover_entity:
#      - cover.sc_dummy3
#    facade_shutter_type_static: mode3
#    # Dynamic configuration inputs
#    brightness_entity: input_number.d01_brightness
#    #brightness_dawn_entity:
#    sun_elevation_entity: input_number.d03_sun_elevation
#    sun_azimuth_entity: input_number.d04_sun_azimuth
#    #sunrise_entity:
#    #sunset_entity:
#    #lock_integration_manual: false
#    #lock_integration_entity: input_boolean.d07_lock_integration
#    #lock_integration_with_position_manual: false
#    #lock_integration_with_position_entity: input_boolean.d08_lock_integration_with_position
#    #lock_height_manual: 0
#    #lock_height_entity: input_number.lock_height_sc_dummy3
#    unlock_integration_entity: input_button.d14_unlock_instances
#    #movement_restriction_height_manual: no_restriction
#    #movement_restriction_height_entity:
#    enforce_positioning_entity: input_button.d13_enforce_positioning
#    # General facade configuration
#    facade_azimuth_static: 320
#    facade_offset_sun_in_static: -45
#    facade_offset_sun_out_static: 45
#    facade_elevation_sun_min_static: 23
#    facade_elevation_sun_max_static: 80
#    facade_shutter_stepping_height_static: 5
#    facade_light_strip_width_static: 0
#    facade_shutter_height_static: 1000
#    facade_neutral_pos_height_manual: 20
#    #facade_neutral_pos_height_entity:
#    facade_modification_tolerance_height_static: 3
#    # Shadow configuration
#    #shadow_control_enabled_entity:
#    shadow_control_enabled_manual: true
#    #shadow_brightness_threshold_winter_entity:
#    #shadow_brightness_threshold_winter_manual: 30000
#    #shadow_brightness_threshold_summer_entity:
#    #shadow_brightness_threshold_summer_manual: 50000
#    #shadow_brightness_threshold_minimal_entity:
#    #shadow_brightness_threshold_minimal_manual: 1000
#    #shadow_after_seconds_entity:
#    shadow_after_seconds_manual: 10
#    #shadow_shutter_max_height_entity:
#    shadow_shutter_max_height_manual: 90
#    #shadow_shutter_look_through_seconds_entity:
#    shadow_shutter_look_through_seconds_manual: 10
#    #shadow_shutter_open_seconds_entity:
#    shadow_shutter_open_seconds_manual: 10
#    #shadow_height_after_sun_entity:
#    shadow_height_after_sun_manual: 10
#    # Dawn configuration
#    #dawn_control_enabled_entity:
#    dawn_control_enabled_manual: true
#    #dawn_brightness_threshold_entity:
#    dawn_brightness_threshold_manual: 5000
#    #dawn_after_seconds_entity:
#    dawn_after_seconds_manual: 10
#    #dawn_shutter_max_height_entity:
#    dawn_shutter_max_height_manual: 50
#    #dawn_shutter_look_through_seconds_entity:
#    dawn_shutter_look_through_seconds_manual: 10
#    #dawn_shutter_open_seconds_entity:
#    dawn_shutter_open_seconds_manual: 10
#    #dawn_height_after_dawn_entity:
#    dawn_height_after_dawn_manual: 80
