#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Required within devcontainer
sudo apt update
sudo apt install -y \
  ffmpeg \
  libturbojpeg0

python3 -m pip install --upgrade pip
python3 -m pip install --requirement requirements_dev.txt
